### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by l7aj-imad** [LaravelDaily/Laravel-Vue-Login-Register#4]
i ma new with this laravel - vue frameworks please when i tried to run the following command : php artisan migrate --seed
 its show me this error .
Database name seems incorrect: You're using the default database name `laravel`. This database does not exist.

    Edit the `.env` file and use the correct database name in the `DB_DATABASE` key.

Please how do i fix it?

**Comment by PovilasKorop** [comment]
@l7aj-imad well, the error is clear and it even says what do to - in your `.env` file with correct database name. I won't help you more than this message, please read how to configure databases in Laravel.

**Comment by l7aj-imad** [comment]
i cloned it in laragon and made sure the links are good but it tells me : could not find driver...

**Comment by PovilasKorop** [comment]
@l7aj-imad it's not issue with our repository, it's issue with your configuration, sorry can't help
